"""adding new column in message table

Revision ID: 054b5151eb42
Revises: 05e30eca99f5
Create Date: 2025-07-10 17:18:48.362497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '054b5151eb42'
down_revision: Union[str, Sequence[str], None] = '05e30eca99f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('owner', sa.String(length=255), nullable=False))
    op.drop_column('messages', 'False')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('False', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('messages', 'owner')
    # ### end Alembic commands ###
