"""adding new column in message table

Revision ID: 05e30eca99f5
Revises: 2b705ce780e6
Create Date: 2025-07-10 17:17:30.958773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05e30eca99f5'
down_revision: Union[str, Sequence[str], None] = '2b705ce780e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('False', sa.String(length=255), nullable=True))
    op.add_column('participants', sa.Column('Partition_id', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('partition_room', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('participants_ibfk_1'), 'participants', type_='foreignkey')
    op.drop_constraint(op.f('participants_ibfk_2'), 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'chatrooms', ['partition_room'], ['room_id'])
    op.create_foreign_key(None, 'participants', 'users', ['Partition_id'], ['user_id'])
    op.drop_column('participants', 'parti_room')
    op.drop_column('participants', 'Parti_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('Parti_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('parti_room', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key(op.f('participants_ibfk_2'), 'participants', 'chatrooms', ['parti_room'], ['room_id'])
    op.create_foreign_key(op.f('participants_ibfk_1'), 'participants', 'users', ['Parti_id'], ['user_id'])
    op.drop_column('participants', 'partition_room')
    op.drop_column('participants', 'Partition_id')
    op.drop_column('messages', 'False')
    # ### end Alembic commands ###
