"""Add room_name to Message model

Revision ID: 6633e27e1916
Revises: 66a80ff31b0f
Create Date: 2025-07-10 22:32:03.817860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6633e27e1916'
down_revision: Union[str, Sequence[str], None] = '66a80ff31b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('room_name', sa.String(length=255), server_default='Stovis Chatroom', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'room_name')
    # ### end Alembic commands ###
