"""Add room_name to Message model

Revision ID: 66a80ff31b0f
Revises: 243d20d8609b
Create Date: 2025-07-10 22:30:17.042739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a80ff31b0f'
down_revision: Union[str, Sequence[str], None] = '243d20d8609b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('room_name', sa.String(length=255), server_default=sa.text('Stovis Chatroom'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'room_name')
    # ### end Alembic commands ###
