"""adding new column in message table

Revision ID: 773b8ce9ab60
Revises: 64010a744e0d
Create Date: 2025-07-10 19:14:39.246836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773b8ce9ab60'
down_revision: Union[str, Sequence[str], None] = '64010a744e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('room_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'room_name')
    # ### end Alembic commands ###
