"""Removing Participants table

Revision ID: e0107f73c6a4
Revises: 176f87e808c3
Create Date: 2025-07-12 12:55:01.840857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0107f73c6a4'
down_revision: Union[str, Sequence[str], None] = '176f87e808c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Partition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partition_room', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Partition_id'], ['users.user_id'], name=op.f('participants_ibfk_2')),
    sa.ForeignKeyConstraint(['partition_room'], ['chatrooms.room_id'], name=op.f('participants_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
